package com.getOpenId.dao;

import com.getOpenId.model.GetopenidUserT;
import com.getOpenId.model.GetopenidUserTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GetopenidUserTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int countByExample(GetopenidUserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int deleteByExample(GetopenidUserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int insert(GetopenidUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int insertSelective(GetopenidUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    List<GetopenidUserT> selectByExample(GetopenidUserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    GetopenidUserT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GetopenidUserT record, @Param("example") GetopenidUserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GetopenidUserT record, @Param("example") GetopenidUserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GetopenidUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getopenid_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GetopenidUserT record);
}